Description: >
  Data Mining Cluster Cloud Formation Template


Parameters:
  StackName:
    Type: String
    Default: Test-Docker-Continous-Integration


Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      CodeCommitRepo:
        default: "CodeCommit Repository Name"
      RepositoryBranch:
        default: "Code Repository Branch Name (master)"
    ParameterGroups:
      - Label:
          default: CodeCommit Repository Configuration
        Parameters:
          - CodeCommitRepo
          - RepositoryBranch


Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/linkedin-skills/vpc.yaml
      Parameters:
        Name: !Ref AWS::StackName
        VpcCIDR: 10.10.0.0/16
        Subnet1CIDR: 10.10.10.0/24
        Subnet2CIDR: 10.10.20.0/24

  EcsCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/linkedin-skills/ecs-cluster.yaml
      Parameters:
        LoadBalancerSecurityGroup: !GetAtt LoadBalancer.Outputs.SecurityGroup
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId
        VpcDefaultSecurityGroup: !GetAtt VPC.Outputs.VpcDefaultSecurityGroup

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/linkedin-skills/load-balancer.yaml
      Parameters:
        Subnets: !GetAtt VPC.Outputs.Subnets
        VpcId: !GetAtt VPC.Outputs.VpcId


Outputs:
  ServiceUrl:
    Description: Stack URL to use. Load Balancer Endpoint
    Value: !GetAtt LoadBalancer.Outputs.ServiceUrl