Description: >
  Service & Task Definition

Parameters:
  Tag:
    Type: String
    Default: latest
  
  DesiredCount:
    Type: Number
    Default: 0
  
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup

  Cluster:
    Type: AWS::ECS::Cluster

Resources:

  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ecs-service-${AWS::StackName}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action: sts.AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain

  
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}--app
      ContainerDefinitions:
        - Name: xcicdoveraws-app
          Image: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Cpu: 49
          Memory: 490
          PortMappings:
            - ContainerPort: 80
          Environment:
            - Name: Tag
              Value: !Ref Tag
  
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref ECSServiceRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: xcicdoveraws-app
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup