Description: >
  VPC CloudFormation definition.


Parameters:
  Name:
    Type: String
  
  VpcCIDR:
    Type: String

  Subnet1CIDR:
    Type: String

  Subnet2CIDR:
    Type: String

  Resources:
    VPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref VpcCIDR
        Tags:
          - Key: Name
            Value: !Ref Name
    
    InternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          - Key: Name
            Value: !Sub InternetGateway-${Name}
    
    InternetGatewayAttachment:
      Type: AWS::EC2::InternetGatewayAttachment
      Properties:
        VpcId: !Ref VPC
        InternetGatewayId: !Ref InternetGateway
        Tags:
          - Key: Name
            Value: !Sub InternetGatewayAttachment-${Name}
    
    Subnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [0, !GetAZs ]
        MapPublicIpOnLaunch: true
        CidrBlock: !Ref Subnet1CIDR
        Tags:
          - Key: Name
            Value: !Sub Public-Subnet1-${Name}

    Subnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref VPC
        AvailabilityZone: !Select [1, !GetAZs ]
        MapPublicIpOnLaunch: true
        CidrBlock: !Ref Subnet2CIDR
        Tags:
          - Key: Name
            Value: !Sub Public-Subnet2-${Name}

    RouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref VPC
        Tags:
          - Key: Name
            Value: !Sub RouteTable-${Name}
    
    DefaultRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId: !Ref RouteTable
        GatewayId: !Ref InternetGateway
        DestinationCidrBlock: 0.0.0.0/0

    Subnet1RouteTableAssociation:
      Type: AWS::EC2::RouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref Subnet1
        Tags: 
          - Key: Name
            Value: !Sub RouteTableAssociation-${Name}
    
    Subnet2RouteTableAssociation:
      Type: AWS::EC2::RouteTableAssociation
      Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref Subnet2


    Outputs:
      Subnets:
        Description: Subnets in a list format comma separated.
        Value: !Join [",", [ !Ref Subnet1, !Ref Subnet2 ]]
      
      Subnet1:
        Description: Subnet1 Created.
        Value: !Ref Subnet1
      
      Subnet2:
        Description: Subnet2 Created.
        Value: !Ref Subnet2

      Az1:
        Description: Availability Zone 1 Created.
        Value: !GetAtt Subnet1.AvailabilityZone

      Az2:
        Description: Availability Zone 2 Created.
        Value: !GetAtt Subnet2.AvailabilityZone

      VpcId:
        Description: VPC Logical Id
        Value: !Ref VPC
      
      VpcDefaultSecurityGroup:
        Description: VPC Default Security Group
        Value: !GetAtt VPC.DefaultSecurityGroup